title: My Sweet Articles
description: A journey through the elegance of art and the sweetness of classic recipes.

# URL Ayarları
# Siten alt klasörde göründüğü için burayı boş bırakıyoruz
baseurl: ""
url: "https://seleneeee-gif.github.io"

# Dosya Dahil Etme (Arka plan için kritik)
include:
  - 1777838696064.png

# Markdown ve Tema
markdown: kramdown
theme: jekyll-theme-minimal

# Link yapısını basitleştiriyoruz (Error vermemesi için)
permalink: /:title.html
